### ISSUE TITLE
Doesn't work with amd

### ISSUE THREAD

**Issue by N6REJ** [mtoohey31/gh-foreach#1]
Got the following error when trying to install via phpstorm terminal
```
gh-foreach unsupported for windows-amd64. Open an issue: `gh issue create -R mtoohey31/gh-foreach -t'Support windows-amd64'`

```

**Comment by N6REJ** [comment]
I'm trying to run for each of the 30+ repos in my organization
```
git rm -r *.nrd
git add *.ber
git commit -m "changing extension"
git push
```

**Comment by mtoohey31** [comment]
That's strange, because the [latest release](https://github.com/mtoohey31/gh-foreach/releases/tag/v0.1.1) includes a build for `windows-amd64`. Do you get this error when running `gh extension install mtoohey31/gh-foreach` or does it show up at another point?

**Comment by N6REJ** [comment]
yes, I got it in git-bash also.  I also tried installed the .exe and that didn't change anything

**Comment by mtoohey31** [comment]
Hmm ok, I'll have to do some testing with Windows, I'm not at my computer right now though. If you have a second, could you check if the same thing happens with the same commands in powershell instead of git-bash? Or was powershell the first place you tried it?

**Comment by N6REJ** [comment]
powershell was the first place.  Thats what phpstorm uses.

**Comment by mtoohey31** [comment]
Ok, I'm not able to reproduce this under windows on my system, which is also amd64. I do have one idea though, is your githib cli up to date? I believe support for precompiled extensions such as this one is a relatively recent feature.

**Comment by N6REJ** [comment]
I have 
```
 C:\windows\system32>git --version
git version 2.34.0.windows.1
 ```
 I JUST updated to 2.34.1
 Can't be wsl2 or anything like that can it?
 
 Even after I updated and used your .exe I get 

![image](https://user-images.githubusercontent.com/1850089/147395637-3c57f5a7-44aa-460e-a0d1-3b784be8486f.png)

**Comment by mtoohey31** [comment]
Can you post the output of `gh --version`?

**Comment by N6REJ** [comment]
![image](https://user-images.githubusercontent.com/1850089/147395686-2cf279e2-7e0f-4c9f-94ea-a769076830a9.png)

**Comment by mtoohey31** [comment]
Does the same issue occur when you update to the latest version?

**Comment by N6REJ** [comment]
yep
![image](https://user-images.githubusercontent.com/1850089/147395817-6a08956f-c6a5-4f9b-9e3f-c40f5dc2e101.png)

**Comment by mtoohey31** [comment]
The extension doesn't seem to be installed now, can you run:

```
gh extension remove foreach # it's ok if this command fails
gh extension install mtoohey31/gh-foreach
```

**Comment by N6REJ** [comment]
ok, now it shows up.. tyvm..
```
Microsoft Windows [Version 10.0.19043.1415]
(c) Microsoft Corporation. All rights reserved.

C:\windows\system32>gh extension remove foreach
no extension found: "C:\\Users\\troy\\AppData\\Local\\GitHub CLI\\extensions\\gh-foreach"

C:\windows\system32>gh extension install mtoohey31/gh-foreach
✓ Installed extension mtoohey31/gh-foreach

C:\windows\system32>gh foreach
execute commands across multiple github repositories

Usage:
  gh-foreach [command]

Available Commands:
  clean       remove cache
  completion  generate the autocompletion script for the specified shell
  help        Help about any command
  run         execute a command

Flags:
  -h, --help   help for gh-foreach

Use "gh-foreach [command] --help" for more information about a command.

C:\windows\system32>
```

**Comment by mtoohey31** [comment]
Np, glad I could help, I'll add a note about the minimum required GitHub CLI version to the README.
